# Generated by Django 4.1.3 on 2023-01-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestmuseeAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='image',
            field=models.ImageField(upload_to='gestmuseeAPP\\static\\img\\conference'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='image',
            field=models.ImageField(upload_to='gestmuseeAPP\\static\\img\\manifestation'),
        ),
    ]
