# Generated by Django 4.1.3 on 2023-01-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestmuseeAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeuvre',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='image',
            field=models.ImageField(upload_to='gestmuseeAPP\\static\\img\\data/artiste'),
        ),
    ]
