# Generated by Django 4.1.3 on 2023-01-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestmuseeAPP", "0002_alter_conference_image_alter_manifestation_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="image",
            field=models.ImageField(
                upload_to="gestmuseeAPP\\static\\img\\data\\conference"
            ),
        ),
        migrations.AlterField(
            model_name="manifestation",
            name="image",
            field=models.ImageField(
                upload_to="gestmuseeAPP\\static\\img\\data\\manifestation"
            ),
        ),
    ]
