# Generated by Django 4.1.3 on 2023-01-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestmuseeAPP", "0003_alter_conference_image_alter_manifestation_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="abonnee",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
